### PR TITLE
fix no session source

### LINKED ISSUE #9974: session-less /source WDA endpoint is not supported anymore?
## The problem

According to [endpoints-wda.md](https://github.com/appium/appium-xcuitest-driver/blob/master/docs/endpoints-wda.md), WebDriverAgent endpoint accepts session-less /source command like http://localhost:8100/source, and Appium1.7.1 actually accepts this session-less endpoint well.

But since 1.7.2, this endpoint returns the following JSON, and cannot get source without session anymore.

```
{
  "value" : "Cannot get 'xml' source of the current application",
  "sessionId" : "E208A1D4-1412-42B9-9869-A6EEBC068ED9",
  "status" : 13
}
```

I confirmed the latest [facebook/WebDriverAgent](https://github.com/facebook/WebDriverAgent) still accepts session-less source command, so I think it is [appium/WebDriverAgent](https://github.com/appium/WebDriverAgent) problem.

I loved WDA session-less /source and /screenshot endpoint very much since I can easily query useful debug information without knowing session detail, and even I use these endpoints for my tool for my business.

I know this end point is not so important for the Appium core feature, but I'm very very glad if you continue to support this endpoint 😣 

## Environment

* Appium version that exhibits the issue: 1.7.2
* Last Appium version that did not exhibit the issue: 1.7.1
* Mac OS X 10.13.2
* Node v7.9.0
* XCode9.2
* iOS simulator for iOS11.2 and iPhone8
* Appium CLI

## Link to Appium logs

[Appium server log](https://gist.github.com/NozomiIto/86f9bfc38f8d4d36355de60f12c1179b).

Files under `/var/folders/5j/86p6_7p53x92gs6w30cxy3_w0000gn/T/com.apple.dt.XCTest/IDETestRunSession-E81D68F9-6211-495C-A640-736923FF0072/WebDriverAgentRunner-4F8923F7-BD17-4A11-8F5E-5FBDAFB501DF`

[StandardOutputAndStandardError.txt](https://gist.github.com/NozomiIto/ae085a91e64f653edd3ae093f410792d).

[Session-WebDriverAgentRunner-2018-01-13_141137-AJHbOq](https://gist.github.com/NozomiIto/faec385cd9d9355ba0e47612ea09b5a4)

## Code To Reproduce Issue

Run the following Python code. It sleeps very long after staring session.

```python
from appium import webdriver
import time

desired_caps = {}
desired_caps['platformName'] = 'iOS'
desired_caps['platformVersion'] = '11.2'
desired_caps['deviceName'] = 'iPhone 8'
desired_caps['automationName'] = 'XCUITest'
desired_caps['app'] = 'com.apple.camera'
desired_caps['showXcodeLog'] = 'true'
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)
time.sleep(3000)
```

Then visit http://localhost:8100/source from the web browser.

### PR DESCRIPTION
**Pull request by KazuCocoa**
This will fix https://github.com/appium/appium/issues/9974 .
What about this? (On my locale, both of with session and session less work.

related: https://github.com/appium/WebDriverAgent/pull/11

### CODE REVIEW

File: WebDriverAgentLib/Commands/FBDebugCommands.m [hunk 1]
```diff
@@ -40,7 +40,7 @@ + (NSArray *)routes
 
 + (id<FBResponsePayload>)handleGetSourceCommand:(FBRouteRequest *)request
 {
-  FBApplication *application = request.session.activeApplication;
+  FBApplication *application = request.session.activeApplication? : [FBApplication fb_activeApplication];
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Commands/FBDebugCommands.m]: Please change to `request.session.activeApplication ?: [FBApplication fb_activeApplication]`

Comment (KazuCocoa) [reply WebDriverAgentLib/Commands/FBDebugCommands.m]: oops, sorry for my mistake... 😅

**Review by mykola-mokhnach — APPROVED** [review]
