### PR TITLE
fix: Tune scrollToVisibleElement

### LINKED ISSUE #15114: iOS Mobile: Scroll does not work
## The problem

The "mobile: scroll" API is not executed as expected. I will describe it in detail.
 
## Environment

* Appium version (or git revision) that exhibits the issue: 1.20.2
* Last Appium version that did not exhibit the issue (if applicable): I can't remember
* Desktop OS/version used to run Appium: macOS (Big Sur 11.1)
* Node.js version (unless using Appium.app|exe): v15.8.0
* Npm or Yarn package manager: yarn 1.22.5
* Mobile platform/version under test: iOS 14.3
* Real device or emulator/simulator: simulator
* Appium CLI or Appium.app|exe: Appium Cli 

## Details

1. TheApp

I got the below error message when using "mobile: scroll" API to scroll to a specific element by predicate string, but it seems not to occur in all other applications.

>  Failed to find scrollable visible parent with 2 visible children

I realized that prescrollSnapshot is always invisible.

https://github.com/appium/WebDriverAgent/blob/master/WebDriverAgentLib/Categories/XCUIElement+FBScrolling.m#L116

```
if (![snapshot isWDVisible]) {
    return NO;
}
```

2. IntegrationApp

It scrolls over the target element until timeout

=> I want to help figure out the bug, but I can't do it yet. If so, please show me some ideas to solve, I will fix it and make a PR.

## Link to Appium logs

https://gist.github.com/zcmgyu/53e859fa6013e64ddaa89117fbc6acbf

## Code To Reproduce Issue [ Good To Have ]

https://github.com/zcmgyu/appium-ios-mobile-scroll-bug

Run below command

1. 

> yarn integration-app

2.

> yarn the-app

### PR DESCRIPTION
**Pull request by Dan-Maor**
We found some instances where scroll to visible did not function correctly and kept scrolling even though the element was found, which required some changes in the scroll to visible functions.

The required changes:
* In `fb_framelessFuzzyMatchesElement` the comparison sometimes yielded false negatives due to the values of the `value` and `placeholderValues` properties not being equal between snapshots - one is returned as a blank string, the other is nil - now taking this into account during the comparison.
* Sometimes, attempting to grab the parent snapshot of the target cell after scrolling is complete causes a stale element reference exception - handled by first using `fb_cachedSnapshot`.
* In the partially visible scroll section - sometimes visibleFrame is not returned correctly from the snapshot (returned as an empty `CGRect`), causing an incorrect final vector. Therefore added a fallback mechanism to retrieve the proper value directly from `FBXCAXClient`.

Also fixes https://github.com/appium/appium/issues/15114

### CODE REVIEW

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 1]
```diff
@@ -128,6 +132,28 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
     }
     return targetCellSnapshot;
 }
+
+- (CGRect) fb_visibleFrameWithFallback
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m]: please remove the space after closing parenthesis to align with the common source style

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 2]
```diff
@@ -128,6 +132,28 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
...
+{
+  CGRect thisVisibleFrame = [self visibleFrame];
+  if (CGRectIsEmpty(thisVisibleFrame))
+  {
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m]: Please move opening brackets to the same line where `if` starts to align with the common source style

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 3]
```diff
@@ -128,6 +132,28 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
...
+    NSDictionary *visibleFrameDict = (NSDictionary*)[self fb_attributeValue:@"XC_kAXXCAttributeVisibleFrame"];
+    if (visibleFrameDict != nil)
+    {
+      id x = [visibleFrameDict valueForKey:@"X"];
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m]: shall we use objectForKey or valueForKey?

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 4]
```diff
@@ -128,6 +132,28 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
...
+      id y = [visibleFrameDict valueForKey:@"Y"];
+      id height = [visibleFrameDict valueForKey:@"Height"];
+      id width = [visibleFrameDict valueForKey:@"Width"];
+      if (x != nil && y != nil && height != nil && width != nil)
+      {
+        thisVisibleFrame = CGRectMake([x doubleValue], [y doubleValue], [width doubleValue], [height doubleValue]);
+      }
+    }
+  }
+  return thisVisibleFrame;
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m:156]: I would rather change the condition to short circuit it, e.g.:

```
CGRect thisVisibleFrame = [self visibleFrame];
if (!CGRectIsEmpty(thisVisibleFrame)) {
  return thisVisibleFrame;
}

....
```

File: WebDriverAgentLib/Categories/XCUIElement+FBScrolling.m [hunk 5]
```diff
@@ -185,9 +185,11 @@ - (BOOL)fb_scrollToVisibleWithNormalizedScrollDistance:(CGFloat)normalizedScroll
   }
 
   // Cell is now visible, but it might be only partialy visible, scrolling till whole frame is visible
-  targetCellSnapshot = self.fb_takeSnapshot.fb_parentCellSnapshot;
-  CGVector scrollVector = CGVectorMake(targetCellSnapshot.visibleFrame.size.width - targetCellSnapshot.frame.size.width,
-                                       targetCellSnapshot.visibleFrame.size.height - targetCellSnapshot.frame.size.height
+  targetCellSnapshot = [([self fb_cachedSnapshot] ?: [self fb_takeSnapshot]) fb_parentCellSnapshot];
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCUIElement+FBScrolling.m:190]: Please add comments here with the explanation (basically copy the one from the PR description)

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 6]
```diff
@@ -145,6 +171,11 @@ inline static BOOL valuesAreEqual(id value1, id value2)
   return value1 == value2 || [value1 isEqual:value2];
 }
 
+inline static BOOL valuesAreEqualOrBlank(id value1, id value2)
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m]: I'd rather start the method name with `areValues...` to align with the other functions style

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.h [hunk 7]
```diff
@@ -87,6 +87,13 @@ NS_ASSUME_NONNULL_BEGIN
 /**! Human-readable snapshot description */
 - (NSString *)fb_description;
 
+/**
+ Returns the snapshot visibleFrame with a fallback to direct attribute retrieval from FBXCAXClient in case of a snapshot fault (nil visibleFrame)
+ 
+ @return the snapshot visibleFrame
+ */
+- (CGRect) fb_visibleFrameWithFallback;
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.h]: extra space here

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 8]
```diff
@@ -128,6 +132,26 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
     }
     return targetCellSnapshot;
 }
+
+- (CGRect)fb_visibleFrameWithFallback
+{
+  CGRect thisVisibleFrame = [self visibleFrame];
+  if (!CGRectIsEmpty(thisVisibleFrame))
+    return thisVisibleFrame;
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m:140]: Please keep curly brackets even if the if block contains one operator. Otherwise we could put both into the same line

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 9]
```diff
@@ -128,6 +132,26 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
...
+  
+  NSDictionary *visibleFrameDict = (NSDictionary*)[self fb_attributeValue:@"XC_kAXXCAttributeVisibleFrame"];
+  if (visibleFrameDict != nil) {
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m]:
```
if (nil == visibleFrameDict) {
  return thisVisibleFrame;
}
...
if (x != nil && y != nil ...
  return CGRectMake ...
}
```

File: WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m [hunk 10]
```diff
@@ -128,6 +132,30 @@ - (XCElementSnapshot *)fb_parentCellSnapshot
...
+  NSDictionary *visibleFrameDict = (NSDictionary*)[self fb_attributeValue:@"XC_kAXXCAttributeVisibleFrame"];
+  if (visibleFrameDict == nil) {
+    return thisVisibleFrame;
+  }
+  
+  id x = [visibleFrameDict objectForKey:@"X"];
+  id y = [visibleFrameDict objectForKey:@"Y"];
+  id height = [visibleFrameDict objectForKey:@"Height"];
+  id width = [visibleFrameDict objectForKey:@"Width"];
+  if (x != nil && y != nil && height != nil && width != nil) {
```
Comment (mykola-mokhnach) [inline WebDriverAgentLib/Categories/XCElementSnapshot+FBHelpers.m:152]: nit: this could be simplified to a single return:
```
return (x != nil && y != nil && height != nil && width != nil)
  ? CGRectMake([x doubleValue], [y doubleValue], [width doubleValue], [height doubleValue])
  : thisVisibleFrame;
```

**Review by mykola-mokhnach — APPROVED** [review]
